### ISSUE TITLE
AppImage features

### ISSUE THREAD

**Issue by probonopd** [cho2/slides#1]
Thanks for your presentation on AppImage at the openSUSE Asia Summit 2017.

Let me take the opportunity to clarify some of the features that you claimed missing from AppImage.

| Feature  | AppImage |
| ------------- | ------------- |
| No software necessary to install a package  | Actually, with AppImage, software is never "installed". The downloaded format is the same as the executed format. I consider this an __advantage__  |
| Shared runtimes  | By design, AppImage allows no dependencies other than what can be expected to be part of all target systems. Like with apps for iOS, everything is either in the OS or in the app. This removes the need for dependency management on the user's end. I consider this an __advantage__ |
| Sandboxing  | AppImage works with various sandboxes such as [Firejail](https://firejail.wordpress.com/documentation-2/appimage-support/). It is not hardcoded toward any particular sandbox. I consider this an __advantage__  |
| Repository support  | Users can just download and run one file without having to manage repositories. I consider this an __advantage__  |
| Central repo  | By design, AppImage is meant to be decentral, so there are no "gatekeepers". An author can put an AppImage onto the download page just like an EXE or DMG. I consider this an __advantage__ |
| Updates  | AppImage supports binary delta updates where you only download the few MB that actually have changed from version to version. Additionally, there is [AppImageHub](https://appimage.github.io/apps/) which lists tested AppImages, and that is managed as a GitHub repository to which everyone can contribute. I consider this an __advantage__ |

Reference:
![compare](https://user-images.githubusercontent.com/2480569/31860625-1ce6d474-b71d-11e7-8cd2-0fb98d81b822.png)

**Comment by probonopd** [comment]
>  automatically embeds update information into AppImages to enable binary delta updates using AppImageUpdate, so user will only get the updated portion of the download package, reducing the amount of download size while updating the package

https://events.opensuse.org/conference/summitasia17/program/proposal/1608

**Comment by cho2** [comment]
Thanks for your additional information @probonopd that i missed. Actually those table refer to https://www.devpy.me/snapcraft-appimage-flatpak/. I should write on my blog so that people can refer to the newest information.

Here is the recap:

| Features | AppImage |
| -------- |:--------:|
| No software necessary to install a package|Yes|
| Shared runtimes|No|
| Sandboxing|Yes|
| Repository support|No|
| Central repo|No|
| Updates|Yes| 

are there any corrections?

**Comment by TheAssassin** [comment]
It's the old "outdated/incomplete/incorrect information on random blog" issue I guess.

Furthermore, you "stole" some slides from the original presentation @probonopd showed on openSUSE conference 2017. I don't recall what license he used, but even if it was licensed (e.g. under the CC-By-NC-SA license the talks usually use), a credit is missing, hence violating copyright either way. I'd ask you to fix that.
You're also publishing a few pictures of people (especially the one of Linus is problematic) without credit information, I'd recommend you to update the screenshot, as the site now contains correct crediting.

Not having a central repo might be presented as an advantage for AppImage by the way, it's a decentralized and fully independent format, unlike snappy/FlatPak, where especially the former is set up as a walled garden.

**Comment by cho2** [comment]
@theassassin thank you for reminds me, I'll write the credits and put revisions on the slides ASAP

**Comment by TheAssassin** [comment]
Great!

**Comment by cho2** [comment]
http://blog.kukuh.syafaat.id/2017/about-AppImage-on-openSUSE-Asia-Summit-2017/

**Comment by probonopd** [comment]
Of course you have my permission to reuse the slides.

**Comment by probonopd** [comment]
Thank you very much for your updates. Please let me know if we can do anything from the project in order to further spread information and increase its use in Asia. Keep up the good work!
